pull_request_rules:
  - name: automatic merge on success
    conditions:
      - check-success=CI / test (20.x)
      - check-success=CI / test (22.x)
      - check-success=CI / test (23.x)
    actions:
      merge:
        method: squash
