name: Run Vitest and Send to Mergify
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x, 23.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      # Pass the matrix node version down to the test environment
      - run: TARGET_NODE=${{ matrix.node-version }} npm test

